server:
  port: 8080

spring:
  datasource:
    url: $jdbc:postgresql://dpg-d6a1r2kr85hc73dktgrg-a:5432/roadsystem
    username: $roadsystem
    password: $oN9IImZtFsVWOZjENn1428QFncmsg2FL
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false

application:
  jwt:
    secret: $superlongrandomsecurejwtsecretkey123456789abcdef
    expiration: 86400000  # 24 hours in ms

cloudinary:
  cloud-name: $dgaq6fj40
  api-key: $338265216481763
  api-secret: $RnTU6JY2Ou8M9H4ICqO6aCAnkPQ

logging:
  level:
    com.smc.roadsystem: DEBUG
    org.springframework.security: INFO
