spring:
  datasource:
    url: $jdbc:postgresql://dpg-d6a1r2kr85hc73dktgrg-a:5432/roadsystem
    username: $roadsystem
    password: $oN9IImZtFsVWOZjENn1428QFncmsg2FL
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
jwt:
  secret: $superlongrandomsecurejwtsecretkey123456789abcdef
  expiration: 86400000
cloudinary:
  cloud-name: $dgaq6fj40
  api-key: $338265216481763
  api-secret: $RnTU6JY2Ou8M9H4ICqO6aCAnkPQ
